server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_depositos
    username: postgres
    password: cami_2025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ms-depositos

springdoc:
  swagger-ui:
    path: /swagger-ui.html

